<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Dacapo ignore tables
    |--------------------------------------------------------------------------
    |
    | This option specifies a table that is not generated by the dacapo:make command.
    |
    */

    'ignore_tables' => [
        'users',
        'password_resets',
        'failed_jobs',
        'personal_access_tokens',
    ],
];
