name: Laravel Pint

on: [pull_request]

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --prefer-dist --working-dir=tools/pint

      - name: Laravel Pint Dry Run
        run: ./tools/pint/vendor/bin/pint -v --test
